import json,shutil
from pathlib import Path
p=Path('research/expansion-20261002/huis-met-beelden');slug='huis-met-de-beelden';out=Path('site/landmarks')/slug;out.mkdir(exist_ok=True)
m=json.loads((p/'model-draft.json').read_text());m.pop('researchOnly');m.update(kind='building',cameraDistance=70,backgroundClearance=.3,placementStatus='approximate-reconstruction',description='Een verdwenen herenhuis aan het Haringvliet, herkenbaar aan twee beelden boven de ingang.',periodNote='Haringvliet 46, circa 1712 gebouwd of vernieuwd; verloren bij het bombardement van 14 mei 1940.',colorNote='Warme zandsteen, lichte kozijnen en een donkere olijfgroene deur volgen Verheuls aquarel uit juli 1934 en de materiaalbeschrijving. Het blijft een benadering, geen exacte historische verfmeting.',wikipediaNote='De bronnen hieronder behandelen dit specifieke verdwenen huis; een algemene pagina over het Haringvliet is geen gebouwbron.')
m['story']='Aan de zuidzijde van het Haringvliet stond een herenhuis dat je al vanaf de straat aan twee beelden boven de deur kon herkennen. De zandstenen gevel had drie vensterassen, hoge verdiepingen en een lagere bovenste verdieping. Het huis werd rond 1712 gebouwd of vernieuwd voor Jacob Noorthey, regent en bewindvoerder van de VOC. Als bouwmeester wordt schilder-architect Adriaan van der Werff genoemd. Via Noortheys dochter raakte het huis verbonden met de familie Groeninx van Zoelen, bekend van Huys ten Donck. Het Rotterdamse huis ging bij het bombardement van 14 mei 1940 verloren. De beelden bleven behouden en kwamen in Museum Rotterdam terecht. Ook onderdelen van het interieur werden gered: panelen en een plafondschildering zijn later gefotografeerd in Haringvliet 98. Dat andere adres is dus niet de oorspronkelijke plek van dit huis. De kaart toont het historische nummer 46. Het model reconstrueert alleen de voorbouw tot het binnenhof. De achterbebouwing en de niet zichtbare historische dakvorm zijn onvoldoende onderbouwd; de vlakke afsluiting is daarom neutraal gehouden. Hoogte en plaatsing blijven benaderingen.'
def src(t,u,s,r='historie',**kw):return dict(title=t,url=u,supports=s,role=r,checkedAt='2026-10-02',**kw)
m['sources']=[src('Stadsarchief · Haringvliet 46–50, XXV-301, 1933','https://proxy.archieven.nl/0/118943BFA50C48F4A5C325704A9408A7','Intacte gevel met drie vensterassen en twee beelden; foto R. Leenheer, 1933, PDM1.0.','beeld'),src('Stadsarchief · Verheul, ingang Haringvliet 46, juli 1934','https://proxy.archieven.nl/0/897CD90DF0484703A2CCDEA514B6A24A','Nummer46, entree, twee beelden en artistieke kleurweergave van zandsteen, kozijnen en deur; aquarel PDM1.0.','beeld'),src('Stadsarchief · L-7017, herplaatst interieur','https://proxy.archieven.nl/0/5F03DCD357A2477680364425C3D4943F','Registratie zegt dat Haringvliet46 getroffen is op14mei1940; panelen/plafond later in98. Ondersteunt onderscheid oorspronkelijke plaats en herplaatst interieur.'),src('Dag van het Kasteel · Brandbommen rondom Huys ten Donck','https://dagvanhetkasteel.nl/brandbommen-rondom-het-huys-ten-donck/','Onder Eindoverwegingen: Huis met de Beelden aan Haringvliet verloren bij bombardement14mei1940; circa1712/Van der Werff/Noorthey, familieverband en geredde beelden in Museum Rotterdam.'),src('Rotterdams Jaarboekje 1966 · A. Bijl Mzn, Het Huis met de Beelden','https://rjb.x-cago.com/GARJB/1966/12/19661231/GARJB-19661231-0334/story.pdf','Geïndexeerde beginpassage: ondergang Haringvliet-zuidzijde46 in mei1940, circa1712 gebouwd of vernieuwd en Bremer zandstenen voorgevel/ingang.',unavailable=True,accessNote='PDF bij controle niet bereikbaar (DNS/502). Beginpassage via zoekindex gecontroleerd; verlies en identiteit tevens ondersteund door de bereikbare bronnen hierboven.'),src('Stadsarchief · historische huisnummerkaart Z18','https://www.archieven.nl/nl/zoeken?mivast=0&mizig=299&miadt=184&miaet=14&micode=4001&minr=39548359&miview=ldt','Nummer46 op perceel244 aan zuidzijde Haringvliet; binnenhof achter voorbouw, tussen44 en48. Basis benaderde historische plaatsing.','kaart')]
m['photos']=[dict(src=f'landmarks/{slug}/foto-1-origineel.jpg',ai=f'landmarks/{slug}/foto-1-ai.webp',aiMaster=f'landmarks/{slug}/foto-1-ai.png',title='Huis met de Beelden · Haringvliet 46 · 1933',shortTitle='Gevel en beelden',date='1933',author='R. Leenheer · Stadsarchief Rotterdam',identifier='Stadsarchief Rotterdam 4202 / XXV-301',license='Public Domain Mark 1.0 volgens Stadsarchief Rotterdam.',licenseUrl='https://creativecommons.org/publicdomain/mark/1.0/',url='https://proxy.archieven.nl/0/118943BFA50C48F4A5C325704A9408A7',sourceChecked='2026-10-02',aiLabel='AI in kleur',aiNote='Afzonderlijke AI-bewerking. Materiaalkleuren mede geïnformeerd door Verheuls aquarel1934; details van beelden, gezichten en kleine opschriften kunnen afwijken. Origineel blijft de bron.')]
shutil.copy2(p/'XXV-301.jpg',out/'foto-1-origineel.jpg')
for f in ['foto-1-ai.webp','foto-1-ai.png','PROMPT-AI-01.txt','BEELDCONTROLE-01.json']:shutil.copy2(p/f,out/f)
shutil.copy2(p/'BRONPAKKET.md',out/'BRONNEN.md')
cat=Path('site/landmarks/catalog.json');j=json.loads(cat.read_text());assert not any(x['id']==slug for x in j);j.append(m);cat.write_text(json.dumps(j,ensure_ascii=False,indent=2)+'\n');print(len(j))
