"""Partition the existing Hoffmanplein planting/path shapes into adjoining areas.

Run with .venv/bin/python landmarks/build-hoffman-ground.py from v1.
The output has no stacked grass/gravel top faces, including path intersections.
"""
import json
from math import cos, sin, tau
from pathlib import Path
from shapely.geometry import Polygon, box
from shapely.ops import unary_union


def ellipse(x, z, rx, rz):
    # Match the existing 48-sided cylinders, whose first vertex points along +z.
    return Polygon([(x + rx*sin(i*tau/48), z + rz*cos(i*tau/48)) for i in range(48)])


beds = unary_union([ellipse(-54, 0, 45, 12), ellipse(60, 0, 62, 14), ellipse(0, 0, 12, 12)])
lawns = unary_union([ellipse(-54, 0, 42, 9.5), ellipse(60, 0, 59, 11.5), ellipse(0, 0, 10.7, 10.7)])
paths = unary_union([
    box(12-221/2, -1.4, 12+221/2, 1.4), box(-4, -4, 4, 4),
    *[box(x-1.35, -12, x+1.35, 12) for x in [-22, 14, 52, 86]],
])
grass = lawns.difference(paths)
footprint = beds.union(paths)
gravel = footprint.difference(grass)
assert grass.is_valid and gravel.is_valid
assert grass.intersection(gravel).area < 1e-8
assert grass.union(gravel).symmetric_difference(footprint).area < 1e-8


def rings(geometry):
    polygons = list(geometry.geoms) if geometry.geom_type == 'MultiPolygon' else [geometry]
    return [[[[round(x, 8), round(z, 8)] for x, z in ring.coords]
             for ring in [p.exterior, *p.interiors]] for p in polygons]


data = {'grass': rings(grass), 'gravel': rings(gravel)}
out = Path(__file__).with_name('hoffman-ground.js')
out.write_text('// Generated by build-hoffman-ground.py. Non-overlapping local x/z polygons.\n'
               'export const hoffmanGround = '+json.dumps(data,separators=(',', ':'))+';\n')
print(f'Hoffmanplein: {grass.area:.2f} m² grass, {gravel.area:.2f} m² gravel; no overlaps or gaps')
