import {chromium} from 'playwright';
import fs from 'node:fs/promises';
import assert from 'node:assert/strict';
import {fileURLToPath} from 'node:url';

const base=(process.env.BASE_URL||'http://127.0.0.1:8765/').replace(/\/?$/,'/');
const output=new URL('../artifacts/',import.meta.url);await fs.mkdir(output,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{}),args:['--enable-webgl','--ignore-gpu-blocklist','--enable-unsafe-swiftshader']});
try{
  const p=await browser.newPage({viewport:{width:1440,height:1000},deviceScaleFactor:1});
  const errors=[],failed=[];
  p.on('pageerror',e=>errors.push(e.message));
  p.on('response',r=>{if(r.status()>=400&&!r.url().endsWith('/favicon.ico'))failed.push([r.status(),r.url()]);});
  await p.goto(base);await p.waitForFunction(()=>window.__rotterdam?.ready,null,{timeout:120000});
  if(await p.locator('#time-intro').isVisible())await p.locator('#intro-old').click();
  const meta=await p.evaluate(()=>({catalog:window.__rotterdam.catalog,stories:window.__rotterdam.stories}));
  assert.ok(meta.catalog.length>0);assert.ok(meta.stories.length>0);
  const item=meta.catalog.find(m=>m.id==='plan-c')||meta.catalog[0];
  await p.locator(`[data-landmark="${item.id}"]`).click();
  assert.equal(await p.locator('#landmark-panel h2').textContent(),item.name);
  assert.equal(await p.locator('.photo-pair').count(),item.photos.length);
  await p.locator('.photo-pair').first().locator('.photo-thumb').last().click();
  await p.waitForFunction(()=>{const im=document.querySelector('.hero-photo');return im?.complete&&im.naturalWidth>0;});
  assert.equal(await p.locator('.hero-photo').getAttribute('src'),item.photos[0].ai);
  await p.locator('.photo-full').click();assert.equal(await p.locator('.image-lightbox').isVisible(),true);
  await p.screenshot({path:fileURLToPath(new URL('desktop-image-viewer.png',output))});
  await p.keyboard.press('Escape');assert.equal(await p.locator('.image-lightbox').isVisible(),false);
  await p.locator('.landmark-close').click();
  await p.locator('#era-now').click();
  await p.waitForFunction(()=>document.body.classList.contains('era-modern'),null,{timeout:120000});
  assert.equal(await p.locator('#modern-buildings').isChecked(),true);
  await p.screenshot({path:fileURLToPath(new URL('desktop-now.png',output))});
  await p.locator('#era-old').click();
  await p.locator('[data-category="stories"]').click();
  const story=meta.stories.find(s=>s.photos?.some(i=>typeof i.ai==='string'));
  await p.locator(`[data-landmark="${story.id}"]`).click();
  assert.equal(await p.locator('#landmark-panel h2').textContent(),story.name);
  await p.locator('.landmark-close').click();await p.locator('[data-category="buildings"]').click();
  await p.setViewportSize({width:390,height:844});
  if(await p.locator('#places-toggle').getAttribute('aria-expanded')!=='true')await p.locator('#places-toggle').click();
  await p.locator(`[data-landmark="${item.id}"]`).click();
  await p.locator('.sheet-expand').click();
  await p.locator('.photo-pair').first().locator('.photo-thumb').last().click();
  await p.waitForFunction(()=>{const im=document.querySelector('.hero-photo');return im?.complete&&im.naturalWidth>0;});
  await p.waitForFunction(()=>{const photo=document.querySelector('.photo-viewer')?.getBoundingClientRect(),bar=document.querySelector('.sheet-bar')?.getBoundingClientRect();return photo&&bar&&photo.top>=bar.bottom-2&&photo.top<=bar.bottom+24;});
  const overflow=await p.evaluate(()=>({page:document.documentElement.scrollWidth>innerWidth,panel:document.querySelector('#landmark-panel').scrollWidth>document.querySelector('#landmark-panel').clientWidth}));
  assert.deepEqual(overflow,{page:false,panel:false});
  await p.screenshot({path:fileURLToPath(new URL('mobile-gallery.png',output))});
  await p.locator('.photo-full').click();assert.equal(await p.locator('.image-lightbox').isVisible(),true);
  await p.screenshot({path:fileURLToPath(new URL('mobile-image-viewer.png',output))});
  assert.deepEqual(errors,[]);assert.deepEqual(failed,[]);
  const report={base,buildings:meta.catalog.length,stories:meta.stories.length,errors,failed,overflow,photoPairs:true,modern3D:true,mobileViewer:true};
  await fs.writeFile(new URL('browser-report.json',output),JSON.stringify(report,null,2));console.log(report);
}finally{await browser.close();}
